packages:
  - "packages/trace-sdk"
  - "packages/trace-server"
  - "packages/trace-admin"
allowBuilds:
  '@nestjs/core': true
  '@nestjs/cli': true
  '@prisma/engines': true
  esbuild: true
  msw: true
  prisma: true
  sqlite3: false
